GCP-339. Encountered new issues after update of scripts, test database, middleware and workbench.
IllegalStateException: Workbench Setting was not found.

Will investigate tomorrow.